// ------------------------------------
// Constants
// ------------------------------------
export const PARTLIB_PART_LIST_BEGIN      = 'PARTLIB_PART_LIST_BEGIN'
export const PARTLIB_PART_LIST_FAILURE    = 'PARTLIB_PART_LIST_FAILURE'
export const PARTLIB_PART_LIST_SUCCESS    = 'PARTLIB_PART_LIST_SUCCESS'

export const PARTLIB_PART_ADD_BEGIN       = 'PARTLIB_PART_ADD_BEGIN'
export const PARTLIB_PART_ADD_FAILURE     = 'PARTLIB_PART_ADD_FAILURE'
export const PARTLIB_PART_ADD_SUCCESS     = 'PARTLIB_PART_ADD_SUCCESS'

export const PARTLIB_PART_EDIT_BEGIN      = 'PARTLIB_PART_EDIT_BEGIN'
export const PARTLIB_PART_EDIT_FAILURE    = 'PARTLIB_PART_EDIT_FAILURE'
export const PARTLIB_PART_EDIT_SUCCESS    = 'PARTLIB_PART_EDIT_SUCCESS'

export const PARTLIB_PART_REMOVE_BEGIN    = 'PARTLIB_PART_REMOVE_BEGIN'
export const PARTLIB_PART_REMOVE_FAILURE  = 'PARTLIB_PART_REMOVE_FAILURE'
export const PARTLIB_PART_REMOVE_SUCCESS  = 'PARTLIB_PART_REMOVE_SUCCESS'