// ------------------------------------
// Constants
// ------------------------------------
export const PARTLIB_WAREHOUSE_LIST_BEGIN      = 'PARTLIB_WAREHOUSE_LIST_BEGIN'
export const PARTLIB_WAREHOUSE_LIST_FAILURE    = 'PARTLIB_WAREHOUSE_LIST_FAILURE'
export const PARTLIB_WAREHOUSE_LIST_SUCCESS    = 'PARTLIB_WAREHOUSE_LIST_SUCCESS'

export const PARTLIB_WAREHOUSE_ADD_BEGIN       = 'PARTLIB_WAREHOUSE_ADD_BEGIN'
export const PARTLIB_WAREHOUSE_ADD_FAILURE     = 'PARTLIB_WAREHOUSE_ADD_FAILURE'
export const PARTLIB_WAREHOUSE_ADD_SUCCESS     = 'PARTLIB_WAREHOUSE_ADD_SUCCESS'