// ------------------------------------
// Constants
// ------------------------------------
export const PARTLIB_SPECIES_LIST_BEGIN      = 'PARTLIB_SPECIES_LIST_BEGIN'
export const PARTLIB_SPECIES_LIST_FAILURE    = 'PARTLIB_SPECIES_LIST_FAILURE'
export const PARTLIB_SPECIES_LIST_SUCCESS    = 'PARTLIB_SPECIES_LIST_SUCCESS'

export const PARTLIB_SPECIES_ADD_BEGIN       = 'PARTLIB_SPECIES_ADD_BEGIN'
export const PARTLIB_SPECIES_ADD_FAILURE     = 'PARTLIB_SPECIES_ADD_FAILURE'
export const PARTLIB_SPECIES_ADD_SUCCESS     = 'PARTLIB_SPECIES_ADD_SUCCESS'

export const PARTLIB_SPECIES_EDIT_BEGIN      = 'PARTLIB_SPECIES_EDIT_BEGIN'
export const PARTLIB_SPECIES_EDIT_FAILURE    = 'PARTLIB_SPECIES_EDIT_FAILURE'
export const PARTLIB_SPECIES_EDIT_SUCCESS    = 'PARTLIB_SPECIES_EDIT_SUCCESS'

export const PARTLIB_SPECIES_REMOVE_BEGIN    = 'PARTLIB_SPECIES_REMOVE_BEGIN'
export const PARTLIB_SPECIES_REMOVE_FAILURE  = 'PARTLIB_SPECIES_REMOVE_FAILURE'
export const PARTLIB_SPECIES_REMOVE_SUCCESS  = 'PARTLIB_SPECIES_REMOVE_SUCCESS'