// ------------------------------------
// Constants
// ------------------------------------
export const ADMINS_USER_LIST_BEGIN      = 'ADMINS_USER_LIST_BEGIN'
export const ADMINS_USER_LIST_FAILURE    = 'ADMINS_USER_LIST_FAILURE'
export const ADMINS_USER_LIST_SUCCESS    = 'ADMINS_USER_LIST_SUCCESS'

export const ADMINS_USER_ADD_BEGIN       = 'ADMINS_USER_ADD_BEGIN'
export const ADMINS_USER_ADD_FAILURE     = 'ADMINS_USER_ADD_FAILURE'
export const ADMINS_USER_ADD_SUCCESS     = 'ADMINS_USER_ADD_SUCCESS'

export const ADMINS_USER_EDIT_BEGIN      = 'ADMINS_USER_EDIT_BEGIN'
export const ADMINS_USER_EDIT_FAILURE    = 'ADMINS_USER_EDIT_FAILURE'
export const ADMINS_USER_EDIT_SUCCESS    = 'ADMINS_USER_EDIT_SUCCESS'

export const ADMINS_USER_REMOVE_BEGIN    = 'ADMINS_USER_REMOVE_BEGIN'
export const ADMINS_USER_REMOVE_FAILURE  = 'ADMINS_USER_REMOVE_FAILURE'
export const ADMINS_USER_REMOVE_SUCCESS  = 'ADMINS_USER_REMOVE_SUCCESS'